export = {
  NODE_ENV: process.env.NODE_ENV || "development",
  CORS_WHITELIST: process.env.CORS_WHITELIST || "INVALID WHITELIST",
  PUPPET_API: process.env.PUPPET_API || "INVALID PUPPET API",
  DATA_API: process.env.DATA_API || "INVALID DATA API",
  TELEGRAM_TOKEN: process.env.TELEGRAM_TOKEN || "INVALID TOKEN",
  TELEGRAM_CHAT_ID: process.env.TELEGRAM_CHAT_ID || "INVALID CHAT ID",
  WEB_URL: process.env.WEB_URL || "INVALID WEB URL"
}
